export const ALL_ENTRIES_REQUEST = 'ALL_ENTRIES_REQUEST';
export const ALL_ENTRIES_SUCCESS = 'ALL_ENTRIES_SUCCESS';
export const ALL_ENTRIES_FAIL = 'ALL_ENTRIES_FAIL'; 

export const NEW_ENTRY_REQUEST = 'NEW_ENTRY_REQUEST';
export const NEW_ENTRY_SUCCESS = 'NEW_ENTRY_SUCCESS';
export const NEW_ENTRY_FAIL = 'NEW_ENTRY_FAIL';

export const  UPDATE_ENTRY_REQUEST = 'UPDATE_ENTRY_REQUEST';
export const  UPDATE_ENTRY_SUCCESS = 'UPDATE_ENTRY_SUCCESS';
export const  UPDATE_ENTRY_FAIL = 'UPDATE_ENTRY_FAIL';

export const DELETE_ENTRY_REQUEST = 'DELETE_ENTRY_REQUEST';
export const DELETE_ENTRY_SUCCESS = 'DELETE_ENTRY_SUCCESS';
export const DELETE_ENTRY_FAIL = 'DELETE_ENTRY_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';